//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zscno.Trackora.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zscno.Trackora.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string AboutTitle_Text {
            get {
                return ResourceManager.GetString("AboutTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有应用 的本地化字符串。
        /// </summary>
        internal static string All_Content {
            get {
                return ResourceManager.GetString("All.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存文件夹大小： 的本地化字符串。
        /// </summary>
        internal static string CacheFolderSize {
            get {
                return ResourceManager.GetString("CacheFolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法发送某些通知。详细信息请查阅日志。 的本地化字符串。
        /// </summary>
        internal static string CanNotSend_Message {
            get {
                return ResourceManager.GetString("CanNotSend.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遇到了一些问题 的本地化字符串。
        /// </summary>
        internal static string CanNotSend_Title {
            get {
                return ResourceManager.GetString("CanNotSend.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看日志 的本地化字符串。
        /// </summary>
        internal static string CheckLog_Content {
            get {
                return ResourceManager.GetString("CheckLog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理缓存 的本地化字符串。
        /// </summary>
        internal static string CleanCache_Content {
            get {
                return ResourceManager.GetString("CleanCache.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理缓存后某些应用的信息需要您使用时后才会加载出来。 的本地化字符串。
        /// </summary>
        internal static string CleanReminder_Text {
            get {
                return ResourceManager.GetString("CleanReminder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已连续使用电脑  的本地化字符串。
        /// </summary>
        internal static string ContinuousReminderText1 {
            get {
                return ResourceManager.GetString("ContinuousReminderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ，建议您休息一会儿。 的本地化字符串。
        /// </summary>
        internal static string ContinuousReminderText2 {
            get {
                return ResourceManager.GetString("ContinuousReminderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续使用时长提醒的提示音： 的本地化字符串。
        /// </summary>
        internal static string ContinuousSoundPicker_Header {
            get {
                return ResourceManager.GetString("ContinuousSoundPicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续使用时长提醒 的本地化字符串。
        /// </summary>
        internal static string ContinuousTimePicker_Header {
            get {
                return ResourceManager.GetString("ContinuousTimePicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色主题 的本地化字符串。
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者工具 的本地化字符串。
        /// </summary>
        internal static string DevelopTitle_Text {
            get {
                return ResourceManager.GetString("DevelopTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法完全清理缓存。详细信息请查阅日志。 的本地化字符串。
        /// </summary>
        internal static string ECanNotCleanCache {
            get {
                return ResourceManager.GetString("ECanNotCleanCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法获取进程的信息。详细信息请查阅日志（见 设置 页面）。 的本地化字符串。
        /// </summary>
        internal static string ECanNotGetInfo {
            get {
                return ResourceManager.GetString("ECanNotGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法获取今天的记录。详细信息请查阅日志（见 设置 页面）。 的本地化字符串。
        /// </summary>
        internal static string ECanNotGetRecord {
            get {
                return ResourceManager.GetString("ECanNotGetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法获取缓存文件夹大小。详细信息请查阅日志。 的本地化字符串。
        /// </summary>
        internal static string ECanNotGetSize {
            get {
                return ResourceManager.GetString("ECanNotGetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法加载进程信息，请联系作者以获取帮助。 的本地化字符串。
        /// </summary>
        internal static string ECanNotInitInfoFilePath {
            get {
                return ResourceManager.GetString("ECanNotInitInfoFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法加载设置，请联系作者以获取帮助。 的本地化字符串。
        /// </summary>
        internal static string ECanNotInitSettings {
            get {
                return ResourceManager.GetString("ECanNotInitSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用的核心部分无法运行，请联系作者以获取帮助。 的本地化字符串。
        /// </summary>
        internal static string ECanNotInitTimer {
            get {
                return ResourceManager.GetString("ECanNotInitTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法记录使用时长。详细信息请查阅日志（见 设置 页面）。 的本地化字符串。
        /// </summary>
        internal static string ECanNotRecordTime {
            get {
                return ResourceManager.GetString("ECanNotRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法管理今天的记录。详细信息请查阅日志（见 设置 页面）。 的本地化字符串。
        /// </summary>
        internal static string ECanNotSetRecord {
            get {
                return ResourceManager.GetString("ECanNotSetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们无法写入进程的信息。详细信息请查阅日志（见 设置 页面）。 的本地化字符串。
        /// </summary>
        internal static string ECanNotWriteInfo {
            get {
                return ResourceManager.GetString("ECanNotWriteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在是  的本地化字符串。
        /// </summary>
        internal static string EndUsingReminderText1 {
            get {
                return ResourceManager.GetString("EndUsingReminderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ，已经到了您指定的停止时间，请您立即休息。 的本地化字符串。
        /// </summary>
        internal static string EndUsingReminderText2 {
            get {
                return ResourceManager.GetString("EndUsingReminderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间到了 的本地化字符串。
        /// </summary>
        internal static string EndUsingReminderTitle {
            get {
                return ResourceManager.GetString("EndUsingReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束使用时间提醒的提示音： 的本地化字符串。
        /// </summary>
        internal static string EndUsingSoundPicker_Header {
            get {
                return ResourceManager.GetString("EndUsingSoundPicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束使用时间提醒 的本地化字符串。
        /// </summary>
        internal static string EndUsingTimePicker_Header {
            get {
                return ResourceManager.GetString("EndUsingTimePicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string ErrorOrWarningTitle {
            get {
                return ResourceManager.GetString("ErrorOrWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出应用 的本地化字符串。
        /// </summary>
        internal static string ExitApp_Text {
            get {
                return ResourceManager.GetString("ExitApp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Home_Content {
            get {
                return ResourceManager.GetString("Home.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日使用时长 的本地化字符串。
        /// </summary>
        internal static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 的本地化字符串。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不记录任何信息的进程名称： 的本地化字符串。
        /// </summary>
        internal static string IgnoredProcesses_Header {
            get {
                return ResourceManager.GetString("IgnoredProcesses.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以英文逗号分隔，无特殊需求不修改。不要让两个逗号连在一起。 的本地化字符串。
        /// </summary>
        internal static string InputReminder_Text {
            get {
                return ResourceManager.GetString("InputReminder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色主题 的本地化字符串。
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用时长排名 的本地化字符串。
        /// </summary>
        internal static string ListTitle_Text {
            get {
                return ResourceManager.GetString("ListTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string OK_Content {
            get {
                return ResourceManager.GetString("OK.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅记录使用时长而不显示在主页的进程名称： 的本地化字符串。
        /// </summary>
        internal static string OnlyTimeProcesses_Header {
            get {
                return ResourceManager.GetString("OnlyTimeProcesses.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选定的时间已经过去了，请重新选择 的本地化字符串。
        /// </summary>
        internal static string PastTime {
            get {
                return ResourceManager.GetString("PastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化 的本地化字符串。
        /// </summary>
        internal static string PersonalizeTitle_Text {
            get {
                return ResourceManager.GetString("PersonalizeTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh_Content {
            get {
                return ResourceManager.GetString("Refresh.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Reset_Content {
            get {
                return ResourceManager.GetString("Reset.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续使用时长的重置时长 的本地化字符串。
        /// </summary>
        internal static string ResetContinuousTimePicker_Header {
            get {
                return ResourceManager.GetString("ResetContinuousTimePicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收起 的本地化字符串。
        /// </summary>
        internal static string Retract {
            get {
                return ResourceManager.GetString("Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个时间是正确的。我们将会在那时提醒您 的本地化字符串。
        /// </summary>
        internal static string RightTime {
            get {
                return ResourceManager.GetString("RightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示音 的本地化字符串。
        /// </summary>
        internal static string RingerTitle_Text {
            get {
                return ResourceManager.GetString("RingerTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示窗口 的本地化字符串。
        /// </summary>
        internal static string ShowWindow_Text {
            get {
                return ResourceManager.GetString("ShowWindow.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        internal static string SystemTheme {
            get {
                return ResourceManager.GetString("SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trackora - 高效管理您的时间 的本地化字符串。
        /// </summary>
        internal static string TaskbarIcon_ToolTipText {
            get {
                return ResourceManager.GetString("TaskbarIcon.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string Test_Content {
            get {
                return ResourceManager.GetString("Test.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的提示音： 的本地化字符串。
        /// </summary>
        internal static string TestContent {
            get {
                return ResourceManager.GetString("TestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用当前主题（更改主题后重启应用生效）： 的本地化字符串。
        /// </summary>
        internal static string ThemePicker_Header {
            get {
                return ResourceManager.GetString("ThemePicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string ThemeTitle_Text {
            get {
                return ResourceManager.GetString("ThemeTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您今天已使用电脑  的本地化字符串。
        /// </summary>
        internal static string TotalReminderText1 {
            get {
                return ResourceManager.GetString("TotalReminderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ，建议您减少电脑的使用。 的本地化字符串。
        /// </summary>
        internal static string TotalReminderText2 {
            get {
                return ResourceManager.GetString("TotalReminderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总使用时长提醒的提示音： 的本地化字符串。
        /// </summary>
        internal static string TotalSoundPicker_Header {
            get {
                return ResourceManager.GetString("TotalSoundPicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总使用时长提醒 的本地化字符串。
        /// </summary>
        internal static string TotalTimePicker_Header {
            get {
                return ResourceManager.GetString("TotalTimePicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用时长提醒 的本地化字符串。
        /// </summary>
        internal static string UsageTimeReminderTitle {
            get {
                return ResourceManager.GetString("UsageTimeReminderTitle", resourceCulture);
            }
        }
    }
}
